services:
  redis:
    image: 'redis@sha256:9d317178eceac8454a2284a9e6df2466b93c745529947f0cd42a0fa9609d7005'
    restart: unless-stopped
    container_name: redis
    sysctls:
      - net.core.somaxconn=65535
    volumes:
      - ./db/:/data/
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  app:
    build: 'app'
    restart: unless-stopped
    container_name: mirrorbits
    depends_on:
      - redis
      - geoipupdate
    expose:
      - 8080
    volumes:
      - /opt/mirror/repo/openmandriva/:/srv/repo/
      - ./mirrorbits.conf:/etc/mirrorbits.conf
      - ./GeoIP:/usr/share/GeoIP
    networks:
      - default

  geoipupdate:
    image: maxmindinc/geoipupdate@sha256:faecdca22579730ab0b7dea5aa9af350bb3c93cb9d39845c173639ead30346d2
    restart: unless-stopped
    container_name: geoipupdate
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=${GEOIPUPDATE_ACCOUNT_ID}
      - GEOIPUPDATE_LICENSE_KEY=${GEOIPUPDATE_LICENSE_KEY}
      - 'GEOIPUPDATE_EDITION_IDS=GeoLite2-ASN GeoLite2-City GeoLite2-Country'
      - GEOIPUPDATE_FREQUENCY=24
    volumes:
      - ./GeoIP:/usr/share/GeoIP
    networks:
      - default

  caddy:
    image: 'caddy@sha256:5f5c8640aae01df9654968d946d8f1a56c497f1dd5c5cda4cf95ab7c14d58648'
    container_name: caddy
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data:/data
      - ./config:/config
    environment:
      - CADDY_EMAIL=siteadmin@openmandriva.org
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]

  cron:
    build: 'cron'
    container_name: nullrsync
    restart: unless-stopped
    volumes:
      - /opt/mirror/repo/openmandriva/:/srv/repo/
