bind 0.0.0.0
protected-mode no
port 6379

maxmemory 28gb
maxmemory-policy allkeys-lru
maxmemory-clients 8gb

appendonly no
save 900 10
save 300 100
save 60 10000
rdbcompression yes
dir /data
logfile "/data/redis.log"

client-query-buffer-limit 2gb
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit pubsub 256mb 64mb 120

timeout 300
tcp-keepalive 60

databases 1

